### ISSUE TITLE
Syntax error when installing

### ISSUE THREAD

**Issue by xobs** [hakril/PythonForWindows#2]
There's some sort of syntax error when running `python .\setup.py install`:

````
[2:49:17 PM] ~/Documents/Code/PythonForWindows> python .\setup.py install
Extracting PythonForWindows-0.4-py3.6.egg to c:\python36\lib\site-packages
  File "c:\python36\lib\site-packages\PythonForWindows-0.4-py3.6.egg\windows\generated_def\windef.py", line 2038
    ERROR_EVT_INVALID_CHANNEL_PATH = make_flag("ERROR_EVT_INVALID_CHANNEL_PATH", 15000L)
                                                                                      ^
SyntaxError: invalid syntax

Adding PythonForWindows 0.4 to easy-install.pth file

Installed c:\python36\lib\site-packages\pythonforwindows-0.4-py3.6.egg
Processing dependencies for PythonForWindows==0.4
Finished processing dependencies for PythonForWindows==0.4
[2:48:26 PM] ~/Documents/Code/PythonForWindows> 
````

**Comment by xobs** [comment]
This leads to an installation that doesn't work:

````python
[2:55:38 PM] ~/Documents/Code/PythonForWindows> python
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import windows
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\smcro\Documents\Code\PythonForWindows\windows\__init__.py", line 19, in <module>
    from windows import winproxy
  File "C:\Users\smcro\Documents\Code\PythonForWindows\windows\winproxy.py", line 7, in <module>
    from windows.generated_def.winstructs import *
  File "C:\Users\smcro\Documents\Code\PythonForWindows\windows\generated_def\__init__.py", line 1, in <module>
    from . import winstructs
  File "C:\Users\smcro\Documents\Code\PythonForWindows\windows\generated_def\winstructs.py", line 1, in <module>
    from windef import *
ModuleNotFoundError: No module named 'windef'
>>>
````

**Comment by hakril** [comment]
Hello,

PythonForWindows only works on python2 for now. I have a long term objectif of making it works on python3 but it's far from done.
I created a github project for the Python3 compatibility requirements that I will try to update as I work on this feature.

**Comment by jgstew** [comment]
It would be useful if there was better documentation on how to install this, as well as having it available in PIP.

**Comment by hakril** [comment]
Hi,
I have added some documentation about Installation via ``setup.py`` in both the ``README.md`` and sphinx documentation. I have also added a check to ``setup.py`` to prevent use on Python3 leading to the broken installation shown by @xobs. 
As for PIP, I do not plan to upload PythonForWindows on Pypi for now.

**Comment by jgstew** [comment]
Thanks for those updates
